import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
export const metadata = {
  title: '3k-Flix',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      
      <body>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
